baseURL = 'https://lmtreser.github.io/boards/'
languageCode = 'es'
title = 'ðŸ“‘ Boards'
theme = 'PaperMod'
description = 'InformaciÃ³n tÃ©cnica acerca de Arduino'
keywords = [ 'Arduino', 'Expressif', 'Raspberry Pi' ]
author = 'Lucas Martin Treser'
DateFormat = 'January 2, 2006'

[params]
defaultTheme = 'light'
disableThemeToggle = false
ShowReadingTime = true
ShowToc = false
TocOpen = true
ShowBreadCrumbs = false
ShowPostNavLinks = true
ShowCodeCopyButtons = true

#[[menu.main]]
#identifier = 'pcb_libs_url'
#name = 'PCB Libs'
#url = 'https://github.com/lmtreser/pcb_libs'
#weight = 10

[[menu.main]]
identifier = 'repositorio'
name = 'cÃ³digo fuente'
url = 'https://github.com/lmtreser/hugo-static-sites/tree/main/boards'
weight = 20

[params.homeInfoParams]
Title = "Tutoriales Arduino"
Content = """
En este mini sitio encontrarÃ¡s diversos tutoriales acerca de la tecnologÃ­a Arduino ðŸš€
"""