baseURL = 'https://lmtreser.github.io/pcb_libs/'
languageCode = 'es'
title = ' DASE'
theme = 'PaperMod'
description = 'Compendio de informaci贸n t茅cnica sobre dise帽o electr贸nico'
keywords = [ 'PCB', 'KiCad', 'DASE', 'Electr贸nica' ]
author = 'Lucas Martin Treser'
DateFormat = 'January 2, 2006'

[params]
defaultTheme = 'light'
disableThemeToggle = false
ShowReadingTime = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = false
ShowPostNavLinks = true
ShowCodeCopyButtons = false

[[menu.main]]
identifier = 'pcb_libs_url'
name = 'PCB Libs'
url = 'https://github.com/lmtreser/pcb_libs'
weight = 10

[[menu.main]]
identifier = 'repositorio'
name = 'C贸digo fuente'
url = 'https://github.com/lmtreser/hugo-static-sites/tree/main/pcb_libs'
weight = 20

[params.homeInfoParams]
Title = "Dise帽o Asistido y Simulaci贸n Electr贸nica"
Content = """
En este mini sitio encontrar谩s un compendio de informaci贸n t茅cnica sobre operaci贸n y programaci贸n de software orientado al dise帽o PCB.
"""